---
cloud_init_user: ''
cloud_init_pkg_x86_64: "https://build.almalinux.org/pulp/content/builds/AlmaLinux-8-x86_64-4866-br/Packages/c/cloud-init-22.1-5.el8.alma.noarch.rpm"
cloud_init_pkg_aarch64: "https://build.almalinux.org/pulp/content/builds/AlmaLinux-8-aarch64-4866-br/Packages/c/cloud-init-22.1-5.el8.alma.noarch.rpm"
cloud_init_pkg_ppc64le: "https://build.almalinux.org/pulp/content/builds/AlmaLinux-8-ppc64le-4866-br/Packages/c/cloud-init-22.1-5.el8.alma.noarch.rpm"
