---
- name: Checking that required variable is defined
  fail: msg="{{ item }} is not defined or empty"
  when: (item is undefined) or (item is none) or (item | trim | length == 0)
  with_items:
    - cloud_init_user

- name: Install cloud-init on x86_64
  dnf:
    name:
      - "{{ cloud_init_pkg_x86_64 }}"
      - cloud-utils-growpart
      - dracut-config-generic
  when: ansible_facts['architecture'] == 'x86_64'

- name: Install cloud-init on AArch64
  dnf:
    name:
      - "{{ cloud_init_pkg_aarch64 }}"
      - cloud-utils-growpart
      - dracut-config-generic
  when: ansible_facts['architecture'] == 'aarch64'

- name: Install cloud-init on ppc64le
  dnf:
    name:
      - "{{ cloud_init_pkg_ppc64le }}"
      - cloud-utils-growpart
      - dracut-config-generic
  when: ansible_facts['architecture'] == 'ppc64le'

- name: Enable cloud-init services
  service:
    name: "{{ item }}"
    enabled: true
  with_items:
    - cloud-config
    - cloud-init
    - cloud-init-local
    - cloud-final

- name: Configure cloud-init user name
  replace:
    dest: /etc/cloud/cloud.cfg
    regexp: '^(\s+name:).*$'
    replace: "\\1 {{ cloud_init_user }}"
